module.exports = angular.module('dryadApp', [
    'ngAnimate',
    'LocalStorageModule',
    'ui.router',
    'ui.router.state.events',
    'oc.lazyLoad',
    'ngCookies',
    'ui.tree',
    'ui.bootstrap',
    'ui.select',
    'ngSanitize',
    'toastr',
    'btford.socket-io',
    'angularMoment',
    'blockUI',
    'angular-timeline',
    'ui.router.tabs',
    'xen3r0.underscorejs'
]);