import 'angular';
import 'jquery';
import 'angular-ui-router';
import 'oclazyload';
import 'angular-animate';
import 'angular-local-storage';
import 'angular-cookies';
// import 'angular-sanitize';
import 'angular-ui-bootstrap';
import '../../node_modules/angular-ui-tree/dist/angular-ui-tree.min.js';
import '../../node_modules/bootstrap/dist/js/bootstrap.min.js';
import '../../node_modules/ui-select/dist/select.min.js';
import '../../node_modules/angular-toastr/dist/angular-toastr.tpls.min.js';
import '../../node_modules/echarts/dist/echarts.min.js';
import '../../node_modules/angular-echarts/dist/angular-echarts.min.js';