import 'angular';
import 'angular-ui-router';
import 'oclazyload';
import 'angular-animate';
import 'angular-local-storage';
import 'angular-cookies';
// import 'angular-sanitize';
import 'angular-ui-bootstrap';
import 'angular-ui-tree';
import 'jquery';
// import 'underscore';
// import 'iscroll';
// import 'bootstrap';