// import 'angular';
import '../node_modules/angular/angular.min';
import '../node_modules/jquery/dist/jquery.min';
import '../node_modules/oclazyload/dist/ocLazyLoad.min';
import '../node_modules/oclazyload/dist/ocLazyLoad.require.min';
import '../node_modules/angular-ui-router/release/angular-ui-router.min';
import '../node_modules/angular-animate/angular-animate.min';
import '../node_modules/angular-local-storage/dist/angular-local-storage.min';
import '../node_modules/angular-cookies/angular-cookies.min';
// import 'angular-animate';
// import 'angular-local-storage';
// import 'angular-cookies';
import 'angular-ui-bootstrap';
// import '../node_modules/angular-ui-bootstrap/dist/ui-bootstrap';